# Generated by Django 3.2.4 on 2021-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210616_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='name',
            field=models.CharField(default='Yeet', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startpage',
            name='urlname',
            field=models.CharField(default='Yeet', max_length=200),
            preserve_default=False,
        ),
    ]
