# Generated by Django 3.2.4 on 2021-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_linkdata_styledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styledata',
            name='data',
            field=models.TextField(),
        ),
    ]
